name : First Workflow

on : [push]

jobs :
  first-job : 
    runs-on : ubuntu-latest
    
    steps : 
      - name : first-command
        run : echo "First command"
      - name : second-cmd
        run : |
          ls -al
          echo "Hello"
